<a href="https://colab.research.google.com/github/Peterogg/Linear_Algebra_Coding_Projects/blob/main/Gram-Schmidt%20Orthonormalization%20Process%20Part%202.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

ll = "loaded"

In [ ]:
# Create a vector
r = np.matrix('1;2;3;4')

r.dot(r)

ValueError: ignored

In [ ]:
# create a vector as an array
s4 = np.array([1, 2, 3, 4])
s4.dot(s4)

30

In [ ]:
# the size of s4
np.sqrt(s4.dot(s4))

5.477225575051661

In [ ]:
# Using the Grahm-Schmidt Orthonormalization Process
r1 = np.array([3, 0, 3, 0])
r2 = np.array([3, 2, 3, 3])
r3 = np.array([-7, -4, -5, -6])
r4 = np.array([-7, -3, -11, 2])


In [ ]:
# find the first nice messy vector
t1 = r1
# subtract off nice basis vectors

# find magnitude of t1
n1 = np.sqrt(t1.dot(t1))

#so u1 = (1/n1) * t1
u1 = (1/n1) * t1
u1

array([0.70710678, 0.        , 0.70710678, 0.        ])

In [ ]:
#verify u1 has size 1 and is orthoganal to all other u vectors
u1.dot(u1)

1.0000000000000002

In [ ]:
# find the first nice messy vector
t2 = r2 - r2.dot(u1) * u1
# subtract off nice basis vectors

# find magnitude of t1
n2 = np.sqrt(t2.dot(t2))

#so u2 = (1/n2) * t2
u2 = (1/n2) * t2
u2
print("The squared size of u2 is  ", u2.dot(u2))
print(u2)

The squared size of u2 is   1.0
[-1.23168186e-16  5.54700196e-01 -1.23168186e-16  8.32050294e-01]


In [ ]:
# find the first nice messy vector
t3 = r3 - r3.dot(u2) * u2 -r3.dot(u1) * u1
# subtract off nice basis vectors

# find magnitude of t1
n3 = np.sqrt(t3.dot(t3))

#so u3 = (1/n3) * t3
u3 = (1/n3) * t3
print(u3)
print("The squared size of u3 is  ", u3.dot(u3))
print("u3.u2 = ", u3.dot(u2))

[-7.07106781e-01 -3.14018492e-16  7.07106781e-01 -6.28036983e-16]
The squared size of u3 is   0.9999999999999998
u3.u2 =  -6.967444759389139e-16


In [ ]:
# find the first nice messy vector
t4 = r4 - r4.dot(u2) * u2 -r4.dot(u1) * u1 - r4.dot(u3) * u3
# subtract off nice basis vectors

# find magnitude of t1
n4 = np.sqrt(t4.dot(t4))

#so u43 = (1/n4) * t4
u4 = (1/n4) * t4
print(u4)
print("The squared size of u4 is  ", u4.dot(u4))
print("u4.u3 = ", u4.dot(u3))

[-1.23168186e-16 -8.32050294e-01  1.23168186e-16  5.54700196e-01]
The squared size of u4 is   1.0000000000000002
u4.u3 =  8.709305949236507e-17


In [ ]:
r4.dot(u4)

3.6055512754639887